version: '3'
services:
  mqtt:
    image: emqx/emqx:4.3.1
    ports:
      - 8083:8083
      - 18083:18083
    environment:
      TZ: Asia/Tokyo
      EMQX_NODE__NAME: emqx@emx1.wator.xyz
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 32M
