version: '3'
services:
  mqtt:
    image: emqx/emqx:4.3.8
    ports:
      - 8083:8083
      - 18083:18083
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./:/ws
      - ./emqx0/etc:/opt/emqx/etc
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 32M
