version: '3'
services:
  gateway:
    image: node:10
    volumes:
      - ./:/home/app
    working_dir: "/home/app"
    environment:
      - MMAX=1G 
    command: ./run.sh
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 64M
  install:
    image: node:10
    volumes:
      - ./:/opt/app
    working_dir: "/opt/app"
    command: ./install_update.sh 
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 32M
        reservations:
          cpus: '0.5'
          memory: 64M
networks:
  outside:
    external:
      name: "host"
