version: '3'
services:
  gateway:
    image: node:10
    volumes:
      - ./:/home/app
    working_dir: "/home/app"
    environment:
      - MMAX=256M 
      - ISDOCKER=true 
    command: ./run.sh
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
networks:
  outside:
    external:
      name: "host"
