version: '3'
services:
  ipfs-dameon:
    image: watorvapor/js-starbian
    volumes:
      - ./:/home/app
    working_dir: "/home/app"
    command: ./run.sh
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
networks:
  outside:
    external:
      name: "host"
