version: '3'
services:
  ipfs-dameon:
    image: node:10
    volumes:
      - ../ws:/home/app/ws
      - ../npm:/home/app/npm
    working_dir: "/home/app/ws"
    environment:
      - MMAX=256M 
    command: ./run.sh
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
networks:
  outside:
    external:
      name: "host"
