version: '3'
services:
  ipfs-dameon:
    image: watorvapor/js-starbian
    volumes:
      - ./:/usr/src/app
    working_dir: "/usr/src/app"
    command: run.sh
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 32M
        reservations:
          cpus: '0.1'
          memory: 16M
networks:
  outside:
    external:
      name: "host"
